# The numpy.random package
***

## Overview of the package
***

## "Simple random data" and "Permutations" functions
***

### Simple random data

#### Integers

> Generator.integers(*low, high=None, size=None, dtype=np.int64, endpoint=False*)

The **integers()** function generates a sequence of random integers. The function takes one required argument, **low**, which defines the upper limit of values which may be returned. If an argument is also passed for the **high** parameter, the argument passed for **low** becomes the lower limit of values which may be returned, and **high** becomes the upper limit.

In [4]:
import numpy.random as np

rng = np.default_rng()
rng.integers(5) # 5 is passed as the "low" argument; all outputs will be between 0 (inclusive) and 5 (exclusive)

3

In [5]:
rng.integers(5, 10) # 5 is the "low" argument, 10 as the "high" argument;
                    # outputs will be between 5 (inclusive) and 10 (exclusive)

7

The **integers()** function returns one integer value, unless an argument is passed for the **size** parameter, in which case a sequence of values of size equal to the value of the argument is returned.

In [6]:
rng.integers(5, size=10) # this will return 10 values between 0 and 5 (exclusive)

array([1, 0, 1, 1, 3, 3, 0, 0, 2, 1], dtype=int64)

A tuple (an unchangeable list of items) can be passed to the **size** parameter if the returned values should be in a multi-dimensional instead of one-dimensional array. The first value of the tuple defines the number of rows in the returned ndarray, and the second value defines the number of columns.

In [8]:
rng.integers(10, size=(3, 4))

array([[7, 3, 7, 3],
       [1, 7, 6, 9],
       [9, 5, 5, 2]], dtype=int64)

The dtype of the result can defined with the **dtype** parameter. The results can be confirmed by passing the **integers()** function inside the **type()** from the standard library.

In [17]:
import numpy
print(rng.integers(10, dtype=numpy.uint8))
type(rng.integers(10, dtype=numpy.uint8))

5


numpy.uint8

The **endpoint** parameter can be passed a Boolean True or False value to change the functioning of the **low** and **high** parameters. If **endpoint** is set to **True**, the value of **high** will be inclusive, so integers of that value can be returned. By default **endpoint** is set to False, so the value of **high** is exclusive, meaning integers of that value cannot be returned (only integers of one increment lower, at maximum).

In [20]:
rng.integers((1, 2), endpoint=True)

array([0, 2], dtype=int64)

#### Random

>  Generator.random(*size=None, dtype=np.float64, out=None*)

The **random()** function returns float values from the interval 0.0 – 1.0. If no arguments are passed to the function's parameters, it will return a single float value.

In [21]:
rng.random()

0.8073554994295814

The **size** parameter is used, as in the **integers()** function, to define the number of values returned, and can take an integer or tuple value as argument. The **dtype** parameter is also used the same as in the **integers()** function, but only *float64* and *float32* are supported.

In [24]:
rng.random(10)

array([0.12982079, 0.51023399, 0.35447712, 0.7614928 , 0.3623529 ,
       0.49695906, 0.45014179, 0.23657541, 0.38061748, 0.71875604])

In [35]:
rng.random(10, dtype="float32")

array([0.95380855, 0.7652706 , 0.91428745, 0.6791067 , 0.7631116 ,
       0.51802695, 0.9997592 , 0.5678816 , 0.07534087, 0.65552557],
      dtype=float32)

The **out** parameter takes a multi-dimensional array to define the shape of the output.

In [49]:
rng.random()

ValueError: Supplied output array is not contiguous, writable or aligned.

#### Choice
> Generator.choice(*a, size=None, replace=True, p=None, axis=0, shuffle=True*)

The ***choice()*** function returns a random sample from a one-dimensional array passed as an argument.

The ***a*** parameter is required, and takes an integer or array as its argument. If an integer is passed, the function runs ***np.arange(x)*** to generate the random value; if an array is passed, the return value is randomly selected from its elements.

In [68]:
choices = rng.integers(10, size=10) # generating a 1d array
print(choices) # printing the array
rng.choice(choices) # choice() selects one element from the array

[2 3 2 0 9 1 5 9 9 8]


9

The ***size*** parameter again defines the output shape. If an integer is passed, the returned array will be of size equal to the value of that integer; if a tuple is passed, the values of the tuple will define the rows and columns of the returned multi-dimensional array.

In [69]:
rng.choice([5, 2, 7, 1, 2, 9,], size=(2,2))

array([[5, 2],
       [9, 5]])

## Distribution functions
***

## Seeds
***

### References